language: python
python: 2.7
sudo: false
env:
  - TOX_ENV=lnx-Django16
  - TOX_ENV=lnx-Django17
  - TOX_ENV=lnx-Django18
addons:
  apt:
    packages:
    - sqlite3
    - libsqlite3-dev
install:
  - pip install 'tox>=2'
script:
  - tox -e $TOX_ENV
